name: push
on:
  push:
    branches:
      - e2e-tests
jobs:
  basic-tests:
    uses: ./.github/workflows/e2e-tests.yaml
    with:
      REQUIRED_TESTS: '[
                          "relevantCVEs",
                          "relevancy_disabled_installation",
                          "relevancy_enabled_stop_sniffing",
                          "relevant_data_is_appended",
                          "relevancy_large_image",
                          "relevancy_extra_large_image",
                          "relevancy_storage_disabled",
                          "relevancy_fix_vuln",
                          "relevancy_python",
                          "relevancy_golang",
                          "relevancy_java",
                          "relevancy_java_and_python"
                       ]'
    secrets: inherit
