name: push
on:
  push:
    branches:
      - e2e-tests
jobs:
  basic-tests:
    uses: ./.github/workflows/e2e-tests.yaml
    with:
      REQUIRED_TESTS: '[
                        "relevantCVEs",
                       ]'
    secrets: inherit
