name: push
on:
  push:
    branches:
      - e2e-tests
jobs:
  basic-tests:
    uses: ./.github/workflows/e2e-tests.yaml
    with:
      REQUIRED_TESTS: '[
                          "vulnerability_scanning", 
                          "vulnerability_scanning_trigger_scan_on_new_image", 
                          "vulnerability_scanning_trigger_scan_public_registry", 
                          "vulnerability_scanning_trigger_scan_public_registry_excluded", 
                          "vulnerability_scanning_trigger_scan_private_quay_registry", 
                          "vulnerability_scanning_triggering_with_cron_job", 
                          "registry_scanning_triggering_with_cron_job", 
                          "ks_microservice_ns_creation",
                          "ks_microservice_on_demand", 
                          "ks_microservice_mitre_framework_on_demand", 
                          "ks_microservice_nsa_and_mitre_framework_demand", 
                          "ks_microservice_triggering_with_cron_job", 
                          "ks_microservice_update_cronjob_schedule", 
                          "ks_microservice_delete_cronjob", 
                          "ks_microservice_create_2_cronjob_mitre_and_nsa",
                          "scan_compliance_score",
                          "vulnerability_scanning_cve_exceptions",
                          "vulnerability_scanning_test_public_registry_connectivity_by_backend",
                          "vulnerability_scanning_test_public_registry_connectivity_excluded_by_backend",
                          "relevantCVEs",
                          "relevancy_disabled_installation",
                          "relevancy_enabled_stop_sniffing",
                          "relevant_data_is_appended",
                          "relevancy_large_image",
                          "relevancy_extra_large_image",
                          "relevancy_storage_disabled",
                          "relevancy_fix_vuln" 
                       ]'
    secrets: inherit
